### ISSUE TITLE
Localhost error

### ISSUE THREAD

**Issue by kaMatPrahlad** [adrianhajdin/zoom-clone#10]
index.browser.es.js:12250 Uncaught (in promise) Error: {"code":-1,"StatusCode":500,"message":"WS failed with code -1 and reason - ","isWSFailure":false}
    at StableWSConnection.connect (index.browser.es.js:12250:27)
    at async StreamClient.connect (index.browser.es.js:13733:24)
    at async Promise.all (:3000/index 1)
    at async StreamClient.connectUser (index.browser.es.js:13414:24)

Anyone can help me to sovle this error

**Comment by Anilraj-Lokku** [comment]
Hello @kaMatPrahlad  i also encountered the same issue. You have to make sure all the .env.local  api key and secret key  from stream and clerk  are correctly pasted.
