### ISSUE TITLE
Not showing anything on localhost:3000

### ISSUE THREAD

**Issue by kaMatPrahlad** [adrianhajdin/zoom-clone#9]
Everything is okay, i'm not getting any error neither in console or nor on my local host:3000 , but whenever im refreshing the page is shows nothing, everything goes blank, i don't know how to resolve this  please somebody help me. i already tried to resolve this many times but still its not working.

**Comment by UMDhodi** [comment]
same issue i faced in sign-in page 

`Uncaught (in promise) Error
    at o._fetch (clerk.browser.js:2:80575)
    at async y._baseMutate (clerk.browser.js:2:81247)
    at async Promise.all (:3000/index 0)
    at async ze.<anonymous> (clerk.browser.js:2:220019)
    at async ze.load (clerk.browser.js:2:199866)
    at async _IsomorphicClerk.loadClerkJS (index.mjs:1191:1)`

**Comment by anisharya16** [comment]
need more information on this, Do you see anything in the terminal or browser's console. Did you double check the routes?
